### ISSUE TITLE
Problem with the minify version

### ISSUE THREAD

**Issue by Aymkdn** [object505/tipso#8] opened 2015-02-25 16:51 UTC
Hi,

I don't know which minified tool you use, but your file https://raw.githubusercontent.com/object505/tipso/master/src/tipso.min.js returns an error: `TypeError: e.G is undefined`

I minified your code with http://refresh-sf.com/ and this time it worked :-)

**Comment by gerrypower** [comment] 2015-02-25 17:40
Had the same issue.

**Comment by object505** [comment] 2015-02-25 18:20
Hello,
The issue is now fixed :)

Thanks :+1:

**Closed by object505** 2015-02-25 18:20 UTC
