### ISSUE TITLE
Position bug

### ISSUE THREAD

**Issue by htulibacki** [object505/tipso#13] opened 2015-05-11 16:10 UTC
Hi,

I think i found a bug. When I set `position` to `bottom` and `width` to `auto`, tooltip does not appear in the middle of the element:

![image](https://cloud.githubusercontent.com/assets/969692/7569370/90ccf5ac-f808-11e4-9e7b-e45873b6b866.png)

And if I set `position` to `top`, everything is fine:

![image](https://cloud.githubusercontent.com/assets/969692/7569414/e7034b1a-f808-11e4-8d99-bd6852f1de70.png)

PS. Thank you very much for all of your work!

**Comment by object505** [comment] 2015-05-11 18:41
Hello,
Thanks for the heads up. The issue is now fixed.
Get the latest version and let me know if you find it working properly :)

**Closed by object505** 2015-05-11 18:41 UTC

**Comment by htulibacki** [comment] 2015-05-11 19:16
Works like a charm. Thank you!
